# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addcommnet.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(10, 10, 512, 218))
        self.calendarWidget.setObjectName("calendarWidget")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.centralwidget, clicked = lambda : self.send_comment())
        self.commandLinkButton.setGeometry(QtCore.QRect(610, 480, 141, 81))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.commandLinkButton.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/send.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commandLinkButton.setIcon(icon)
        self.commandLinkButton.setIconSize(QtCore.QSize(60, 60))
        self.commandLinkButton.setDefault(False)
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(40, 240, 711, 241))
        self.textEdit.setObjectName("textEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AddCommentWindow"))
        self.commandLinkButton.setText(_translate("MainWindow", "Send"))


    def setuser_name(self, user_name):
        self.user_name = user_name


    @staticmethod
    def show_error(message, type_mesasge, user_name):

        msg = QtWidgets.QMessageBox()
        msg.setIcon(type_mesasge)
        msg.setText(f"Hello {user_name}")
        msg.setInformativeText(message)
        msg.setWindowTitle("Message")
        msg.exec_()

    def send_comment(self):
        import persian
        import json
        import os
        date = str(self.calendarWidget.selectedDate().toPyDate())
        date = date.replace('-','.')
        comment = self.textEdit.toPlainText()

        if  os.path.exists(f"F:\\project_ap_99472068\\comments\\{self.user_name}") == False:
            os.makedirs(f"F:\\project_ap_99472068\\comments\\{self.user_name}")


        try:
            with open(f"F:\\project_ap_99472068\\comments\\{self.user_name}\\{date}.txt", 'w', encoding = 'utf-8') as f:
                f.write(comment)
                self.show_error("Comment sent!",QtWidgets.QMessageBox.Information,self.user_name)

        except:
            self.show_error("Comment didn't send!", QtWidgets.QMessageBox.Critical, self.user_name)


        self.textEdit.setText('')





if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
